### ISSUE TITLE
errors with mocha 6 when using mochawesome/cypress

### ISSUE THREAD

**Issue by YOU54F** [YOU54F/mocha-junit-reporters#1]
Mocha 6 introduced breaking changes in v6.0.

https://github.com/mochajs/mocha/releases/tag/v6.0.0

```
#3149: Drop Node.js v4.x support (@outsideris)
#3556: Changes to command-line options (@boneskull):
--grep and --fgrep are now mutually exclusive; attempting to use both will cause Mocha to fail instead of simply ignoring --grep
--compilers is no longer supported; attempting to use will cause Mocha to fail with a link to more information
-d is no longer an alias for --debug; -d is currently ignored
#3275: --watch-extensions no longer implies js; it must be explicitly added (@TheDancingCode)
#2908: tap reporter emits error messages (@chrmod)
#2819: When conditionally skipping in a before hook, subsequent before hooks and tests in nested suites are now skipped (@bannmoore)
#627: Emit filepath in "timeout exceeded" exceptions where applicable (@boneskull)
#3556: lib/template.html has moved to lib/browser/template.html (@boneskull)
#2576: An exception is now thrown if Mocha fails to parse or find a mocha.opts at a user-specified path (@plroebuck)
#3458: Instantiating a Base-extending reporter without a Runner parameter will throw an exception (@craigtaub)
#3125: For consumers of Mocha's programmatic API, all exceptions thrown from Mocha now have a code property (and some will have additional metadata). Some Error messages have changed. Please use the code property to check Error types instead of the message property; these descriptions will be localized in the future. (@craigtaub)
```

the two we may be interested in 

https://github.com/mochajs/mocha/pull/3458
https://github.com/mochajs/mocha/issues/3125

This reporter needs some work to support these changes, to allow mochawesome/cypress to perform reports

PR tracking the mocha 6 upgrade and failing CI test run

https://github.com/YOU54F/cypressio-docker-typescript/pull/15

```
TypeError: Cannot read property 'failures' of undefined
    at MochaJUnitReporter.getXml (/root/app/e2e/node_modules/mocha-junit-reporter/index.js:291:22)
    at MochaJUnitReporter.flush (/root/app/e2e/node_modules/mocha-junit-reporter/index.js:238:18)
    at MochaJUnitReporter.<anonymous> (/root/app/e2e/node_modules/mocha-junit-reporter/index.js:144:10)
    at emitOne (events.js:120:20)
    at Runner.emit (events.js:210:7)
    at Reporter.emit (/root/.cache/Cypress/3.1.3/Cypress/resources/app/packages/server/lib/reporter.js:239:55)
    at Object.server.startWebsockets.onMocha (/root/.cache/Cypress/3.1.3/Cypress/resources/app/packages/server/lib/project.js:296:22)
    at Socket.<anonymous> (/root/.cache/Cypress/3.1.3/Cypress/resources/app/packages/server/lib/socket.js:237:36)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /root/.cache/Cypress/3.1.3/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by YOU54F** [comment]
```
  Runner {
  domain: null,
  _events:
   { start: [ [Function], [Function: bound ] ],
     suite: [ [Function], [Function: bound ] ],
     'test end': [Function],
     pass: [ [Function], [Function: bound ] ],
     fail: [ [Function], [Function: bound ] ],
     end: [ [Function], [Function: bound ] ],
     pending: [Function] },
  _eventsCount: 7,
  _maxListeners: undefined,
  stats:
   { suites: 2,
     tests: 0,
     passes: 2,
     pending: 0,
     failures: 2,
     start: 2019-03-27T02:23:43.754Z,
     end: 2019-03-27T02:23:43.754Z,
     duration: 0 },
  _currentSuite:
   { title: 'Another suite!',
     tests: [ 1 ],
     suites: [],
     parent:
      { title: 'Foo Bar module',
        root: false,
        tests: [Array],
        suites: [] } } }
```

mocha 5

**Comment by YOU54F** [comment]
```
  Runner {
  domain: null,
  _events:
   { pass: [ [Function], [Function: bound ] ],
     fail: [ [Function], [Function: bound ] ],
     start: [Function: bound ],
     suite: [Function: bound ],
     end: [Function: bound ] },
  _eventsCount: 5,
  _maxListeners: undefined,
  _currentSuite:
   { title: 'Another suite!',
     tests: [ 1 ],
     suites: [],
     parent:
      { title: 'Foo Bar module',
        root: false,
        tests: [Array],
        suites: [] } } }

  0 passing (21ms)
  1 failing
```

mocha 6

**Comment by YOU54F** [comment]
See for refactor

https://github.com/mochajs/mocha/commit/52b9a5fb97bc3a6581dc6538aa0092276e71ea41#diff-b3b53682a18f203ac8d29b0e277cad26

**Comment by YOU54F** [comment]
https://github.com/mochajs/mocha/blob/52b9a5fb97bc3a6581dc6538aa0092276e71ea41/docs/api-tutorials/custom-reporter.md

**Comment by YOU54F** [comment]
Mocha allows you to define and use custom reporters install via `npm`.

For example, if `mocha-foo-reporter` was published to the npm registry, you could install it via `npm install mocha-foo-reporter --save-dev`, then use it via `mocha --reporter mocha-foo-reporter`.

## Example Custom Reporter

If you're looking to get started quickly, here's an example of a custom reporter:



```js
// my-reporter.js
'use strict';

const Mocha = require('mocha');
const {
  EVENT_RUN_BEGIN,
  EVENT_RUN_END,
  EVENT_TEST_FAIL,
  EVENT_TEST_PASS,
  EVENT_SUITE_BEGIN,
  EVENT_SUITE_END
} = Mocha.Runner.constants;

// this reporter outputs test results, indenting two spaces per suite
class MyReporter {
  constructor(runner) {
    this._indents = 0;
    const stats = runner.stats;

    runner
      .once(EVENT_RUN_BEGIN, () => {
        console.log('start');
      })
      .on(EVENT_SUITE_BEGIN, () => {
        this.increaseIndent();
      })
      .on(EVENT_SUITE_END, () => {
        this.decreaseIndent();
      })
      .on(EVENT_TEST_PASS, test => {
        // Test#fullTitle() returns the suite name(s)
        // prepended to the test title
        console.log(`${this.indent()}pass: ${test.fullTitle()}`);
      })
      .on(EVENT_TEST_FAIL, (test, err) => {
        console.log(
          `${this.indent()}fail: ${test.fullTitle()} - error: ${err.message}`
        );
      })
      .once(EVENT_RUN_END, () => {
        console.log(`end: ${stats.passes}/${stats.passes + stats.failures} ok`);
      });
  }

  indent() {
    return Array(this._indents).join('  ');
  }

  increaseIndent() {
    this._indents++;
  }

  decreaseIndent() {
    this._indents--;
  }
}

module.exports = MyReporter;
```



To use this reporter, execute `mocha --reporter /path/to/my-reporter.js`.

For further examples, the built-in reporter implementations are the [best place to look](https://github.com/mochajs/mocha/tree/master/lib/reporters). The [integration tests](https://github.com/mochajs/mocha/tree/master/test/reporters) may also be helpful.

## The `Base` Reporter Class

[Base] is an "abstract" class. It contains console-specific settings and utilities, commonly used by built-in reporters. Browsing the built-in reporter implementations, you may often see static properties of [Base] referenced.

It's often useful--but not necessary--for a custom reporter to extend [Base].

## Statistics

Mocha adds a `stats` property of type [StatsCollector](/api/module-lib_stats-collector.html) to the reporter's `Runner` instance (passed as first argument to constructor).

## Events

A reporter should listen for events emitted from the `runner` (a singleton instance of [Runner]).

The event names are exported from the `constants` property of `Mocha.Runner`:

| Constant             | Event Name  | Event Arguments | Description                                                                                 |
| -------------------- | ----------- | --------------- | ------------------------------------------------------------------------------------------- |
| `EVENT_RUN_BEGIN`    | `start`     | _(n/a)_         | Execution will begin.                                                                       |
| `EVENT_RUN_END`      | `end`       | _(n/a)_         | All [Suite]s, [Test]s and [Hook]s have completed execution.                                 |
| `EVENT_DELAY_BEGIN`  | `waiting`   | _(n/a)_         | Waiting for `global.run()` to be called; only emitted when [delay] option is `true`.        |
| `EVENT_DELAY_END`    | `ready`     | _(n/a)_         | User called `global.run()` and the root suite is ready to execute.                          |
| `EVENT_SUITE_BEGIN`  | `suite`     | `Suite`         | The [Hook]s and [Test]s within a [Suite] will be executed, including any nested [Suite]s.   |
| `EVENT_SUITE_END`    | `suite end` | `Suite`         | The [Hook]s, [Test]s, and nested [Suite]s within a [Suite] have completed execution.        |
| `EVENT_HOOK_BEGIN`   | `hook`      | `Hook`          | A [Hook] will be executed.                                                                  |
| `EVENT_HOOK_END`     | `hook end`  | `Hook`          | A [Hook] has completed execution.                                                           |
| `EVENT_TEST_BEGIN`   | `test`      | `Test`          | A [Test] will be executed.                                                                  |
| `EVENT_TEST_END`     | `test end`  | `Test`          | A [Test] has completed execution.                                                           |
| `EVENT_TEST_FAIL`    | `fail`      | `Test`, `Error` | A [Test] has failed or thrown an exception.                                                 |
| `EVENT_TEST_PASS`    | `pass`      | `Test`          | A [Test] has passed.                                                                        |
| `EVENT_TEST_PENDING` | `pending`   | `Test`          | A [Test] was skipped.                                                                       |
| `EVENT_TEST_RETRY`   | `retry`     | `Test`, `Error` | A [Test] failed, but is about to be retried; only emitted if the `retry` option is nonzero. |

**Please use these constants** instead of the event names in your own reporter! This will ensure compatibility with future versions of Mocha.

> It's important to understand that all `Suite` callbacks will be run _before_ the [Runner] emits `EVENT_RUN_BEGIN`. Hooks and tests, however, won't run until _after_ the [Runner] emits `EVENT_RUN_BEGIN`.

[runner]: /api/mocha.runner
[test]: /api/mocha.test
[hook]: /api/mocha.hook
[suite]: /api/mocha.suite
[base]: /api/mocha.reporters.base
[delay]: /#delayed-root-suite

**Comment by YOU54F** [comment]
Just fixed this and proposed the following 2 PR's

https://github.com/stanleyhlng/mocha-multi-reporters/pull/58
https://github.com/michaelleeallen/mocha-junit-reporter/pull/80

My branch tracking the changes, with failing builds with mocha 6 pre and post fix is here

https://github.com/YOU54F/cypressio-docker-typescript/pull/15/files

If you do want to move up to mocha 6, you can pull my forked branch in the interim, whilst we wait for the maintainers of the source repo to review/merge/release the PR

```
    "mocha": "^6.0.0",
    "mocha-junit-reporter": "YOU54F/mocha-junit-reporter#master",
    "mocha-multi-reporters": "YOU54F/mocha-multi-reporters#master",
```

**Comment by YOU54F** [comment]
I've now updated, tested and released updated modules that fix this with mocha 6, but also retains backwards compatibility with mocha 5 and earlier versions.

https://www.npmjs.com/package/cypress-multi-reporters
https://www.npmjs.com/package/mocha-junit-reporters

[Example against Mocha 5](https://github.com/YOU54F/cypress-docker-typescript/pull/32)
[Example against Mocha 6](https://github.com/YOU54F/cypress-docker-typescript/pull/22/)

the changes required are minimal 

`npm i mocha-junit-reporters`
`npm i cypress-multi-reporters`

in reporterOpts.json

```json
{
  "reporterEnabled": "mocha-junit-reporters, mochawesome",
  "mochaJunitReportersReporterOptions": {
    "mochaFile": "cypress/reports/junit/test_results[hash].xml",
    "toConsole": false
  },
  "mochawesomeReporterOptions": {
    "reportDir": "cypress/reports/mocha",
    "quiet": true,
    "overwrite": false,
    "html": false,
    "json": true
  }
} 
```

in cypress.json

```json
{
  ...
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporterOpts.json"
  }
```

See https://github.com/YOU54F/cypress-docker-typescript/pull/22/files

Hopefully the PR's will be merged in the source repo's soon but for now, enjoy
